# Generated by Django 4.2.7 on 2024-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
