# Generated by Django 4.2.7 on 2024-02-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_userlocation_latitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='liststorerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('storename', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
