# Generated by Django 4.2.7 on 2024-03-05 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0006_alter_mycart_productid_alter_mycart_serviceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='towingrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('clientlocation', models.CharField(max_length=150)),
                ('additionalprobleminfo', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
