# Generated by Django 4.2.7 on 2024-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_towingrequest_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towingrequest',
            name='storeid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
