# Generated by Django 4.2.7 on 2024-03-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_towingrequest_storeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towingrequest',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='towingrequest',
            name='serviceid',
            field=models.CharField(max_length=80),
        ),
    ]
