# Generated by Django 4.2.7 on 2024-03-14 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_towingrequest_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='towingrequest',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towingrequest',
            name='totalprice',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
