# Generated by Django 4.2.7 on 2024-03-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_towingrequest_date_towingrequest_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towingrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
