# Generated by Django 4.2.7 on 2024-03-16 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_productrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
