# Generated by Django 4.2.7 on 2024-03-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_productrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='storeid',
        ),
    ]
