# Generated by Django 4.2.7 on 2024-03-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_remove_productrequest_storeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='towingrequest',
            name='completed',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
