# Generated by Django 4.2.7 on 2024-04-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_towingrequest_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='completed',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
