# Generated by Django 4.2.7 on 2024-01-26 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='servicestoredata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_store_details', models.BooleanField(default=False)),
                ('ownername', models.CharField(blank=True, max_length=70, null=True)),
                ('storename', models.CharField(blank=True, max_length=80, null=True)),
                ('storecontact', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('openingtime', models.TimeField(blank=True, null=True)),
                ('closingtime', models.TimeField(blank=True, null=True)),
                ('ownercontact', models.BigIntegerField(blank=True, null=True)),
                ('storeaddress', models.CharField(blank=True, max_length=180, null=True)),
                ('storelicencedocument', models.FileField(blank=True, null=True, upload_to='servicestoredata/licence_doc/')),
                ('ownersdocument', models.FileField(blank=True, null=True, upload_to='servicestoredata/aadhar_doc/')),
                ('imageofstore', models.FileField(blank=True, null=True, upload_to='servicestoredata/servicestore_image/')),
                ('storeestablishment', models.DateField(blank=True, null=True)),
                ('gstno', models.CharField(blank=True, max_length=15, null=True)),
                ('hsnsac', models.IntegerField(blank=True, null=True)),
                ('is_activee', models.IntegerField(blank=True, default=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
