# Generated by Django 4.2.7 on 2024-01-27 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicelisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('avgtime', models.CharField(max_length=60)),
                ('servicename', models.CharField(max_length=80)),
                ('serviceimage', models.FileField(upload_to='servicestoredata/service_image/')),
                ('serviceprice', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
