# Generated by Django 4.2.7 on 2024-02-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicestore', '0002_servicelisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelisting',
            name='category',
        ),
    ]
