# Generated by Django 4.2.7 on 2024-02-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicestore', '0003_remove_servicelisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelisting',
            name='user',
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicestore.servicestoredata'),
            preserve_default=False,
        ),
    ]
