# Generated by Django 4.2.7 on 2024-02-13 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicestore', '0004_remove_servicelisting_user_servicelisting_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelisting',
            name='store',
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
