# Generated by Django 4.2.7 on 2024-02-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicestore', '0005_remove_servicelisting_store_servicelisting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicestore.servicestoredata'),
            preserve_default=False,
        ),
    ]
