# Generated by Django 4.2.7 on 2024-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicestore', '0006_servicelisting_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='towable',
            field=models.BooleanField(default=0),
        ),
    ]
