# Generated by Django 4.2.7 on 2024-04-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicestore', '0008_servicelisting2'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='servicelisting2',
        ),
    ]
