# Generated by Django 4.2.7 on 2024-04-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicestore', '0009_servicelisting_active_delete_servicelisting2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestoredata',
            name='hsnsac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
