# Generated by Django 4.2.7 on 2024-01-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='closingtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='gstno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='hsnsac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='is_activee',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='openingtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='ownercontact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='ownername',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='storeaddress',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='storecontact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='storeestablishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='storename',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
