# Generated by Django 4.2.7 on 2024-02-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storedata_latitude_storedata_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecategory',
            name='type',
        ),
    ]
