# Generated by Django 4.2.7 on 2024-02-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_usecategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.storedata'),
            preserve_default=False,
        ),
    ]
