# Generated by Django 4.2.7 on 2024-02-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_storedata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storedata',
            table=None,
        ),
    ]
