# Generated by Django 4.2.7 on 2024-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_storedata_hsnsac'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
